export const ORDER_REQ = "ORDER_REQ";
export const ORDER_SUCCES = "ORDER_SUCCES";
export const ORDER_FAIL = "ORDER_FAIL";

export const ALL_ORDER_REQ = "ALL_ORDER_REQ";
export const ALL_ORDER_SUCCES = "ALL_ORDER_SUCCES";
export const ALL_ORDER_FAIL = "ALL_ORDER_FAIL";

export const DELETE_ORDERS_RQUEST = "DELETE_ORDERS_RQUEST";
export const DELETE_ORDERS_SUCCES = "DELETE_ORDERS_SUCCES";
export const DELETE_ORDERS_FAIL = "DELETE_ORDERS_FAIL";
export const DELETE_ORDERS__RESET = "DELETE_ORDERS__RESET";

export const UPDATE_ORDERS_RQUEST = " UPDATE_ORDERS_RQUEST";
export const UPDATE_ORDERS_SUCCES = " UPDATE_ORDERS_SUCCES";
export const UPDATE_ORDERS_FAIL = " UPDATE_ORDERS_FAIL";
export const UPDATE_ORDERS__RESET = " UPDATE_ORDERS__RESET";

export const ORDER_DETAILS_RQUEST = "ORDER_DETAILS_RQUEST";
export const ORDER_DETAILS_SUCCES = " ORDER_DETAILS_SUCCES";
export const ORDER_DETAILS_FAIL = " ORDER_DETAILS_FAIL";

export const ORDER_USER_RQUEST = "ORDER_USER_RQUEST";
export const ORDER_USER_SUCCES = " ORDER_USER_SUCCES";
export const ORDER_USER_FAIL = " ORDER_USER_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
