export const ALL_PRODUCT_REQ = "ALL_PRODUCT_REQ";
export const ALL_PRODUCT_SUCCES = "ALL_PRODUCT_SUCCES";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQ = "PRODUCT_DETAILS_REQ";
export const PRODUCT_DETAILS_SUCCES = "PRODUCT_DETAILS_SUCCES";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CREATE_PRODUCT_REQ = "CREATE_PRODUCT_REQ";
export const CREATE_PRODUCT_SUCCES = "CREATE_PRODUCT_SUCCES";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";

export const ADMIN_PRODUCT_REQ = "ADMIN_PRODUCT_REQ";
export const ADMIN_PRODUCT_SUCCES = "ADMIN_PRODUCT_SUCCES";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQ = "UPDATE_PRODUCT_REQ";
export const UPDATE_PRODUCT_SUCCES = "UPDATE_PRODUCT_SUCCES";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const DELETE_PRODUCT_REQ = "DELETE_PRODUCT_REQ";
export const DELETE_PRODUCT_SUCCES = "DELETE_PRODUCT_SUCCES";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const REVIEW_PRODUCT_REQ = "REVIEW_PRODUCT_REQ";
export const REVIEW_PRODUCT_SUCCES = "REVIEW_PRODUCT_SUCCES";
export const REVIEW_PRODUCT_FAIL = "REVIEW_PRODUCT_FAIL";
export const REVIEW_PRODUCT_RESET = " REVIEW_PRODUCT_RESET";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = " REMOVE_CART_ITEM";
export const SHIPPING_INFO = "SHIPPING_INFO";

export const CLEAR_ERROR = "CLEAR_ERROR";
