export const ADD_SELLER_REQ = "ADD_SELLER_REQ";
export const ADD_SELLER_SUCCES = "ADD_SELLER_SUCCES";
export const ADD_SELLER_FAIL = "ADD_SELLER_FAIL";
export const ADD_SELLER_RESET = "ADD_SELLER_RESET";
